version: "3"
services:
  kmua:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./data:/kmua/data
      - ./logs:/kmua/logs
      - ./config.yml:/kmua/config.yml