version: "3"
services:
  kmua:
    image: ghcr.io/krau/kmua-bot:v2
    container_name: kmua-v2-main
    init: true
    volumes:
      - ./data:/kmua/data
      - ./logs:/kmua/logs
    environment:
      - TZ=Asia/Shanghai
      - KMUA_TOKEN="你的token"
      - KMUA_OWNERS=[]
      - KMUA_PICKLE_PATH="./data/data.pickle"