version: "3"
services:
  kmua:
    image: ghcr.io/krau/kmua-bot:main
    init: true
    container_name: kmua-main
    volumes:
      - ./data:/kmua/data
      - ./logs:/kmua/logs
      - ./config.yml:/kmua/config.yml