version: "3"
services:
  kmua:
    image: ghcr.io/krau/kmua-bot:v2
    container_name: kmua-main
    restart: always
    volumes:
      - ./data:/kmua/data # 不要修改此挂载
      - ./logs:/kmua/logs
    environment:
      - TZ=Asia/Shanghai
      - KMUA_TOKEN="你的token"
      - KMUA_OWNERS=[] # 主人id, 是一个数组
      - KMUA_LOG_LEVEL="INFO"
      - KMUA_DB_URL="sqlite:///./data/kmua.db"
      - KMUA_BILILINK_CONVERT_API="" # 可选，用于转换b站链接